import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIST = ROOT / "dist"
AMBIGUOUS = {"opengl32.dll", "d3d9.dll", "loader.exe", "log.txt", "eax.dll", "steam.dll"}


def valid(entry):
    if not entry.get("enabled"):
        return False
    path = entry.get("path", "")
    digest = entry.get("hash", "")
    return (path.startswith("../") and re.fullmatch(r"[0-9a-fA-F]{8}|UNKNOWN", digest) is not None)


def render(entry):
    path = entry["path"].replace('"', "")
    digest = entry["hash"].upper()
    basename = Path(path).name.lower()
    action = entry.get("action", "log")
    if digest == "UNKNOWN" or basename in AMBIGUOUS or action != "ban":
        command = "echo '[OldFragAC] review userid=[userid] file=[file_name] md5=[file_md5hash]'"
        return f'"{path}"\t{digest}\t"{command}"'
    reason = re.sub(r"[^A-Za-z0-9 _.-]", "", entry.get("reason", "Cheat detected"))[:80]
    command = f"fb_ban 525600 [userid] '[OldFragAC] {reason}'"
    return f'"{path}"\t{digest}\t"{command}"\tBREAK'


def main():
    cfg = json.loads((ROOT / "config.json").read_text(encoding="utf-8"))
    entries = json.loads((ROOT / "data/curated_signatures.json").read_text(encoding="utf-8"))
    unique = {}
    for entry in entries:
        if valid(entry):
            unique[(entry["path"].lower(), entry["hash"].lower())] = entry
    rules = [render(x) for x in unique.values()]
    cap = int(cfg["max_rules_per_group"])
    DIST.mkdir(exist_ok=True)
    manifest = {"schema": 1, "groups": []}
    for i in range(0, len(rules), cap):
        name = f"resources_{i // cap + 1}.ini"
        body = "; Generated by oldfrag-anticheat. Do not edit.\n" + "\n".join(rules[i:i + cap]) + "\n"
        target = DIST / name
        target.write_text(body, encoding="utf-8")
        manifest["groups"].append({"file": name, "rules": len(rules[i:i + cap]), "sha256": hashlib.sha256(body.encode()).hexdigest()})
    (DIST / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()

